### ISSUE TITLE
Any plans for web and other platforms?

### ISSUE THREAD

**Issue by giorgio79** [Baseflow/flutter-geocoding#52]
## 🚀 Feature Requests

Hello,

Any plans for web and other platforms?
I was looking at other reverse geocoding packages, and the codebases are pretty similar (https://github.com/bazrafkan/google_geocoding) . Might be just enabling sg on the package page? 

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by giorgio79** [comment]
Created pull request for web, looks like all is needed is adding the platform 
https://github.com/Baseflow/flutter-geocoding/pull/53

I tried to fork the repo and then install it via pubspec, but getting this weird error:
(Probably because the project has a funky setup with some kind of plugin interface...
In pubspec I put
```
  geocoding:
    git:
      url: https://github.com/giorgio79/flutter-geocoding/tree/master/geocoding/
      ref: master
      publish_to: none
  flutter_chat_ui: ^1.0.2
  #https://pub.dev/packages/flutter_chat_ui
```

```

Git error. Command: `git clone --mirror https://github.com/giorgio79/flutter-geocoding/tree/master/geocoding/ C:\Users\User\AppData\Local\Pub\Cache\git\cache\geocoding-f2a0042d85b3a12c080f9fc7de72aa6f8fe2ce3d`
stdout: 
stderr: Cloning into bare repository 'C:\Users\User\AppData\Local\Pub\Cache\git\cache\geocoding-f2a0042d85b3a12c080f9fc7de72aa6f8fe2ce3d'...
fatal: repository 'https://github.com/giorgio79/flutter-geocoding/tree/master/geocoding/' not found
exit code: 128

pub get failed (server unavailable) -- attempting retry 1 in 1 second...

```
